<?php
$data = [
    'lang_1' => 'The other side is offline',
    'lang_2' => 'You cannot invite yourself',
    'lang_3' => 'Operation cannot be blank',
    'lang_4' => 'Invitee ID cannot be blank',
    'lang_5' => 'Invitation sharing succeeded',
    'lang_6' => 'Add succeeded',
    'lang_7' => 'Rejection succeeded',
    'lang_8' => 'You have hung up',
    'lang_9' => 'The other side hangs up',
    'lang_10' => 'You have already shared live broadcast',
    'lang_11' => 'No response for a long time, the user is offline',
    'lang_12' => 'You have invited this user, please wait for a moment',
    'lang_13' => 'The user is busy now, please try later',
    'lang_14' => 'First time to invite this user, please wait for a moment',
    'lang_15' => 'Hang up succeeded',
    'lang_16' => 'Unexpected exit of the initiator',
    'lang_17' => 'Live studio ID cannot be blank',
    'lang_18' => 'The room dismissed once the initiator exits',
    'lang_19' => 'User ID cannot be blank',
    'lang_20' => 'Single user quit',
    'lang_21' => 'All users cleared',
    'lang_22' => 'User or room ID cannot be blank',
    'lang_23' => 'Room created',
    'lang_24' => "This room doesn't exist",
    'lang_25' => 'You have entered the room',
    'lang_26' => 'The initiator quit the room',
    'lang_27' => 'Single user quit the room',
    'lang_28' => 'Inviter destroys room, room does not exist',
];
return $data;